apiVersion : apps/v1
kind: Deployment
metadata:
  name: swiphfbootcampappwithkubernetes 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiphfbootcampappwithkubernetes
  template:
    metadata:
      labels:
        app: swiphfbootcampappwithkubernetes 
    spec:
      containers:
        - name: swiphfbootcampappwithkubernetes 
          image: containerregistryweek10.azurecr.io/swiphfbootcampappwithkubernetes
          ports:
          - containerPort: 8080
          env:
          -  name: COOKIE_ENCRYPT_PWD
             value: $(COOKIE_ENCRYPT_PWD)
          -  name: HOST
             value: $(HOST)
          -  name: HOST_URL
             value: $(HOST_URL)
          -  name: NODE_ENV
             value: $(NODE_ENV)
          -  name: OKTA_CLIENT_ID
             value: $(OKTA_CLIENT_ID)
          -  name: OKTA_CLIENT_SECRET
             value: $(OKTA_CLIENT_SECRET)
          -  name: OKTA_ORG_URL
             value: $(OKTA_ORG_URL)
          -  name: PG_DATABASE
             value: $(PG_DATABASE)
          -  name: PG_HOST
             value: $(PG_HOST)
          -  name: PG_PASSWORD
             value: $(PG_PASSWORD)
          -  name: PG_PORT
             value: $(PG_PORT)
          -  name: PG_USERNAME
             value: $(PG_USERNAME)
          -  name: PORT
             value: '8080'
