apiVersion : apps/v1
kind: Deployment
metadata:
  name: swiphfbootcampappwithkubernetes 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiphfbootcampappwithkubernetes
  template:
    metadata:
      labels:
        app: swiphfbootcampappwithkubernetes 
    spec:
      containers:
        - name: swiphfbootcampappwithkubernetes 
          image: containerregistryweek10.azurecr.io/swiphfbootcampappwithkubernetes
          ports:
          - containerPort: 8080
          env:
          - name: COOKIE_ENCRYPT_PWD
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: COOKIE_ENCRYPT_PWD
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: HOST
          - name: HOST_URL
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: HOST_URL
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: NODE_ENV
          - name: OKTA_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: OKTA_CLIENT_ID
          - name: OKTA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: OKTA_CLIENT_SECRET
          - name: OKTA_ORG_URL
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: OKTA_ORG_URL
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: PG_DATABASE
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: PG_HOST
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: PG_PASSWORD
          - name: PG_PORT
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: PG_PORT
          - name: PG_USERNAME
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: PG_USERNAME
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: PORT
