apiVersion : apps/v1
kind: Deployment
metadata:
  name: swiphfbootcampappwithkubernetes 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiphfbootcampappwithkubernetes
  template:
    metadata:
      labels:
        app: swiphfbootcampappwithkubernetes 
    spec:
      containers:
        - name: swiphfbootcampappwithkubernetes 
          image: containerregistryweek10.azurecr.io/swiphfbootcampappwithkubernetes
          ports:
          - containerPort: 8080
          env:
          - name: COOKIE_ENCRYPT_PWD
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: COOKIE_ENCRYPT_PWD
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: HOST
          - name: HOST_URL
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: HOST_URL
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                name: secretvariables
                key: NODE_ENV

